# Generated by Django 3.2.5 on 2021-07-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20210726_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(default='default', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='women',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='women.category', verbose_name='Категория'),
        ),
    ]
