# Generated by Django 3.2.5 on 2021-07-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20210728_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='women.category', verbose_name='Категория'),
        ),
    ]
